/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.18.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace ThriftSpecification.Shared
{

  public partial class Work : TBase
  {
    private int _a;
    private int _b;
    private global::ThriftSpecification.Shared.Operation _operation;

    public int A
    {
      get
      {
        return _a;
      }
      set
      {
        __isset.a = true;
        this._a = value;
      }
    }

    public int B
    {
      get
      {
        return _b;
      }
      set
      {
        __isset.b = true;
        this._b = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="global::ThriftSpecification.Shared.Operation"/>
    /// </summary>
    public global::ThriftSpecification.Shared.Operation Operation
    {
      get
      {
        return _operation;
      }
      set
      {
        __isset.operation = true;
        this._operation = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool a;
      public bool b;
      public bool operation;
    }

    public Work()
    {
      this._a = 0;
      this.__isset.a = true;
    }

    public Work DeepCopy()
    {
      var tmp0 = new Work();
      if(__isset.a)
      {
        tmp0.A = this.A;
      }
      tmp0.__isset.a = this.__isset.a;
      if(__isset.b)
      {
        tmp0.B = this.B;
      }
      tmp0.__isset.b = this.__isset.b;
      if(__isset.operation)
      {
        tmp0.Operation = this.Operation;
      }
      tmp0.__isset.operation = this.__isset.operation;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                A = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                B = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                Operation = (global::ThriftSpecification.Shared.Operation)await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp1 = new TStruct("Work");
        await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
        var tmp2 = new TField();
        if(__isset.a)
        {
          tmp2.Name = "a";
          tmp2.Type = TType.I32;
          tmp2.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async(A, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.b)
        {
          tmp2.Name = "b";
          tmp2.Type = TType.I32;
          tmp2.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async(B, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.operation)
        {
          tmp2.Name = "operation";
          tmp2.Type = TType.I32;
          tmp2.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async((int)Operation, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Work other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.a == other.__isset.a) && ((!__isset.a) || (global::System.Object.Equals(A, other.A))))
        && ((__isset.b == other.__isset.b) && ((!__isset.b) || (global::System.Object.Equals(B, other.B))))
        && ((__isset.operation == other.__isset.operation) && ((!__isset.operation) || (global::System.Object.Equals(Operation, other.Operation))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.a)
        {
          hashcode = (hashcode * 397) + A.GetHashCode();
        }
        if(__isset.b)
        {
          hashcode = (hashcode * 397) + B.GetHashCode();
        }
        if(__isset.operation)
        {
          hashcode = (hashcode * 397) + Operation.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp3 = new StringBuilder("Work(");
      int tmp4 = 0;
      if(__isset.a)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("A: ");
        A.ToString(tmp3);
      }
      if(__isset.b)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("B: ");
        B.ToString(tmp3);
      }
      if(__isset.operation)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("Operation: ");
        Operation.ToString(tmp3);
      }
      tmp3.Append(')');
      return tmp3.ToString();
    }
  }

}
